package ifrs.dev2.buyer.api;



import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import javax.print.attribute.standard.Media;
import java.awt.*;

@RestController // This means that this class is a Controller
@RequestMapping(path="/api/local") // This means URL's start with /demo (after Application path)
public class LocalController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ifrs.dev2.buyer.repositorios.LocalRepository repositorio;

    @PostMapping(
            value = "pesquisar"
            ,consumes = {MediaType.APPLICATION_JSON_VALUE}
            ,produces = {MediaType.APPLICATION_JSON_VALUE}
    ) // Map ONLY POST Requests
    public @ResponseBody
    ifrs.dev2.buyer.dados.Local Pesquisar (@RequestBody ifrs.dev2.buyer.dados.Local entidade) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        repositorio.save(entidade);

        return entidade;
    }
}

