package ifrs.dev2.buyer.api;

import ifrs.dev2.buyer.dados.Classe;
import ifrs.dev2.buyer.dados.DadoInterface;
import ifrs.dev2.buyer.dados.Produto;
import ifrs.dev2.buyer.erros.ErroBase;
import ifrs.dev2.buyer.erros.ErroItem;
import ifrs.dev2.buyer.respostas.ClasseResponse;
import ifrs.dev2.buyer.respostas.ProdutoResponse;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Sort;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import javax.persistence.Id;
import javax.print.attribute.standard.Media;
import java.util.Comparator;
import java.util.List;

@RestController // This means that this class is a Controller
@RequestMapping(path="/api/produto") // This means URL's start with /demo (after Application path)
public class ProdutoController  {

    long ID_NAO_ENCONTRADO = -1;

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ifrs.dev2.buyer.repositorios.ProdutoRepository repositorio;

    @PostMapping(
            value = "salvar"
            , consumes = {MediaType.APPLICATION_JSON_VALUE}
            , produces = {MediaType.APPLICATION_JSON_VALUE}
    ) // Map ONLY POST Requests

    public @ResponseBody
    ifrs.dev2.buyer.respostas.ProdutoResponse Salvar(@RequestHeader HttpHeaders headers, @RequestBody ifrs.dev2.buyer.dados.Produto entidade) throws Exception {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        try
        {
            repositorio.save(entidade);

            return new ProdutoResponse( entidade,null,null);
        }

        catch (Exception e)
        {
            String msg = "deu merda";

            ErroItem item = new ErroItem("",msg,-1L);
            //ErroBase erroBase = new ErroBase(e);
            ErroBase erroBase = new ErroBase(item);

            ProdutoResponse retorno = new  ProdutoResponse(null, erroBase, null) ;
            return retorno;
        }
    }


    //@CrossOrigin() // origins = "http://localhost:3000"
    @GetMapping(
            value = "pesquisar"
            , produces = {MediaType.APPLICATION_JSON_VALUE}
    )
    public @ResponseBody
    ProdutoResponse Pesquisar(@RequestHeader HttpHeaders headers,@RequestParam String nome) // @RequestHeader HttpHeaders headers,
    {
        try
        {
            List<Produto> retorno = null;

            if(nome.length() > 0)
            {
                retorno = repositorio.findByNomeContaining(nome);
            }
            else
            {
                retorno = repositorio.findByNomeContaining(nome);
            }

            retorno.sort(Comparator.comparing(Produto::getNome ));

            return new ProdutoResponse( null,null,retorno);
        }
        catch(Exception e)
        {
            String msg = "deu merda";

            ErroItem item = new ErroItem("",msg,-1L);
            //ErroBase erroBase = new ErroBase(e);
            ErroBase erroBase = new ErroBase(item);

            ProdutoResponse retorno = new  ProdutoResponse(null, erroBase, null) ;
            return retorno;
        }
    }

    @GetMapping(
            path="consultar/{id}"
            , produces = {MediaType.APPLICATION_JSON_VALUE}
    )
    public @ResponseBody
    ProdutoResponse Consultar(@RequestHeader HttpHeaders headers, @PathVariable Long id) {

        Produto retorno = new Produto();
        try
        {
            retorno  = repositorio.findById(id).get();

            return new ProdutoResponse( retorno,null,null);
        }

        catch (Exception e)
        {
            retorno.setId(ID_NAO_ENCONTRADO);

            String msg = "deu merda";

            ErroItem item = new ErroItem("",msg,-1L);
            //ErroBase erroBase = new ErroBase(e);
            ErroBase erroBase = new ErroBase(item);

            return  new  ProdutoResponse(null, erroBase, null) ;

        }

    }

    @GetMapping(
            path="excluir/{id}"
            ,produces = {MediaType.APPLICATION_JSON_VALUE}
    )
    public @ResponseBody  Produto Excluir(@RequestHeader HttpHeaders headers, @PathVariable Long   id) {

        Produto retorno = new Produto();
        try
        {
            retorno  = repositorio.findById(id).get();
            repositorio.deleteById(retorno.getId());
        }

        catch (Exception e)
        {
            retorno.setId(ID_NAO_ENCONTRADO);
        }

        return retorno;
    }

    void ErroLancar() throws Exception {
        throw new Exception("deu merda");
    }


    @GetMapping(
            value = "listar"
            , produces = {MediaType.APPLICATION_JSON_VALUE}
    )
    public @ResponseBody
    ProdutoResponse Listar(@RequestHeader HttpHeaders headers)
    {
        try
        {
            String nome="";
            List<Produto> retorno = retorno = repositorio.findByNomeContaining(nome);

            retorno.sort(Comparator.comparing(Produto::getNome ));

            return new ProdutoResponse( null,null,retorno);
        }
        catch(Exception e)
        {
            String msg = "deu merda";

            ErroItem item = new ErroItem("",msg,-1L);
            //ErroBase erroBase = new ErroBase(e);
            ErroBase erroBase = new ErroBase(item);

            ProdutoResponse retorno = new  ProdutoResponse(null, erroBase, null) ;
            return retorno;
        }
    }


}